name: Sync AniList Stats
on:
  schedule:
    - cron: '0 0 1 * *' # Run on the 1st of every month
  workflow_dispatch: # Allow manual triggers

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Sync AniList Data
        run: bun run sync:anilist
        env:
          ANILIST_TOKEN: ${{ secrets.ANILIST_TOKEN }}

      - name: Commit and Push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add src/data/anilist.json
          git commit -m "chore: update anilist stats [skip ci]" || echo "No changes to commit"
          git push
